### ISSUE TITLE
assets中忘记提交"fonts/Lobster-1.4.otf");

### ISSUE THREAD

**Issue by Evanhlx** [xiaohaibin/KotlinEnjoyLife#1]
Caused by: java.lang.RuntimeException: Font asset not found fonts/Lobster-1.4.otf
        at android.graphics.Typeface.createFromAsset(Typeface.java:206)
        at com.stx.xhb.enjoylife.widget.CustomTextView.init(CustomTextView.java:37)
        at com.stx.xhb.enjoylife.widget.CustomTextView.<init>(CustomTextView.java:23)

 /**
     * 设置字体
     * @param context
     */
    private void init(Context context){
        AssetManager assets = context.getAssets();
        Typeface font = Typeface.createFromAsset(assets, "fonts/Lobster-1.4.otf");
        setTypeface(font);
    }

**Comment by xiaohaibin** [comment]
已提交
